### ISSUE TITLE
Naming conflict?

### ISSUE THREAD

**Issue by RXminuS** [Sidekick-AI/dataflow#1]
There's quite a popular product by Google (Dataflow) based on Apache Beam that operates in a very similar space. I personally was quite confused when i stumbled upon this package because I thought it was a beam/dataflow port in Rust. Maybe an idea to change package names while still early to avoid confusion later on if takes off?

I don't think Dataflow is a registered trademark in the US by Google currently...but just FYI in the US it's "first use" not "first to register" that prevails.

**Comment by jafioti** [comment]
This is more of a small personal project, so I don't think it'll ever get to a point where we're stealing any traffic from google :)
